language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
env:
  - DB=mysql
  - DB=postgresql
before_script:
  - mysql -e 'create database redirector_dummy_test; create database redirector_dummy_development;'
  - psql -c 'create database redirector_dummy_test' -U postgres
  - psql -c 'create database redirector_dummy_development' -U postgres
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - bundle exec rake db:migrate
